assign [class="teams-for-linux"] $ws1
assign [class="org.wezfurlong.wezterm"] $ws2
assign [window_role="browser"] $ws3
assign [class="Spotify"] $ws4

for_window [class="popupa"]\
	floating enable,\
	resize set 50 ppt 75 ppt,\
	move position center

for_window [class="cursor-pane"]\
	floating enable,\
	resize set 10 ppt 20 ppt,\
	move position center, \
	sticky enable
