#!/usr/bin/env bash

set -xeuo pipefail

state_file="${TMPDIR:-/tmp}/latest-cursor-pane"

mapfile -t panes < <(
    tmux list-panes -aF '#{pane_id} #{pane_current_command}' |
        awk '$2 ~ /agent/ { print $1 }'
)

if ((${#panes[@]} == 0)); then
    rm -f "$state_file"
    exit 1
fi

last_pane=""
if [[ -f "$state_file" ]]; then
    read -r last_pane <"$state_file" || true
fi

selected_pane="${panes[0]}"
if [[ -n "$last_pane" ]]; then
    for i in "${!panes[@]}"; do
        if [[ "${panes[$i]}" == "$last_pane" ]]; then
            selected_pane="${panes[$(((i + 1) % ${#panes[@]}))]}"
            break
        fi
    done
fi

tmux switch-client -t "$selected_pane"
printf '%s\n' "$selected_pane" >"$state_file"
