require("samharju.set")
require("samharju.remap")
require("samharju.qflist_maps")
require("samharju.commands")
require("samharju.lazy")
require("samharju.status")
require("samharju.terminal")
require("samharju.session")
require("samharju.notes")
require("samharju.bufpop")

vim.cmd.colorscheme("quitequiet-transparent")
