#!/usr/bin/env bash

set -eo pipefail

usage() {
    echo "$0 <connect|disconnect> <device>"
    exit 1
}

[[ ! "$1" =~ connect|disconnect ]] && usage

if [[ "$1" == disconnect ]]; then
    bluetoothctl disconnect
    exit 0
fi

if [[ "$1" == connect ]]; then
    dev=$(bluetoothctl devices | rg -i "$2" | cut -d' ' -f 2)
    bluetoothctl connect "$dev"
fi
