#!/usr/bin/env bash

set -x

if rg -q open /proc/acpi/button/lid/LID/state; then
    xrandr --output eDP-1 --auto
else
    xrandr --output eDP-1 --off
fi

cmd="xrandr"
for mon in $(xrandr --listmonitors | rg "^ \d" | awk '{print $4}' | sort); do
    if [[ -n "$prev" ]];then
        cmd+=" --output $mon --auto --left-of $prev"
    else
        cmd+=" --output $mon --auto --primary"
    fi
    prev="$mon"
done

$cmd
/home/sharju/.local/scripts/fixbackground
