#!/usr/bin/env bash

fzf \
    --prompt ' ...' \
    --bind 'load:change-prompt:> ' \
    --query "$1" \
    --header='all folders' \
    --header-first \
    --tmux \
    --info=hidden < <(
        fd --follow --hidden --ignore-file "$XDG_CONFIG_HOME/git/ignore" --type directory \
            . "$HOME"
    )
