#!/usr/bin/env bash

git remote update
local=$(git rev-parse HEAD)
remote=$(git rev-parse '@{upstream}')
base=$(git merge-base HEAD '@{upstream}')


if [ "$local" = "$remote" ]; then
    echo "Up to date" >&2
    exit 0
elif [ "$local" = "$base" ]; then
    echo "Need to pull" >&2
    git log 'HEAD^..@{upstream}' --oneline
elif [ "$remote" = "$base" ]; then
    echo "Need to push" >&2
    git log '@{upstream}^..HEAD' --oneline
else
    echo "Diverged"
    git log 'HEAD^..@{upstream}' --oneline
    git log '@{upstream}^..HEAD' --oneline
fi

exit 1
