#!/usr/bin/env bash

fd --hidden --no-ignore "\.git$" \
    "${@:2}" \
    | sed -re 's|/.git/?$||' \
    | fzf \
    --prompt ' ...' \
    --bind 'load:change-prompt:> ' \
    --query "$1" \
    --header='git projects' \
    --header-first \
    --tmux \
    --info=hidden \
    --preview 'cd {}; git branch --color=always' \
    --preview-window 'right,40%'
