#!/usr/bin/env bash

fzf \
    --prompt ' ...' \
    --bind 'load:change-prompt:> ' \
    --query "$1" \
    --header='git projects' \
    --header-first \
    --tmux \
    --info=hidden \
    --preview 'cd {}; git branch --color=always' \
    --preview-window 'right,40%' < <(
        fd --follow --hidden --no-ignore "\.git$" \
            "${@:2}" |
            sed -re 's|/.git/?$||'
    )
