#!/usr/bin/env bash

set -ex

if [[ "$1" == "git" ]]; then
    project=$(
        gitprojectfind "git" \
            "$HOME/.local/share" \
            "$HOME/git" \
            "$HOME/plugins" ||
            true
    )
else
    project=$(folderfind "$1" || true)
fi

if [ -z "$project" ]; then
    exit 0
fi

sessari=$(realpath --relative-to="$HOME" "$project")
sessari=${sessari//./_}

if ! tmux has-session -t="$sessari" 2>/dev/null; then
    tmux new-session -ds "$sessari" -c "$project"
fi

if [ -z "$TMUX" ]; then
    tmux attach -t "$sessari"
else
    tmux switch-client -t "$sessari"
fi
tmux refresh-client -S
