#!/usr/bin/env bash


set -e
hosts=$(rg '^[\w\-\.]+\s+(\S+)' -or "\$1" /etc/hosts | sort)


target="$(echo "$hosts" | fzf --header "ssh to host" --header-first --info hidden --tmux || true)"
if [[ -z "$target" ]]; then
    exit 0
fi

ts="${target//_/-}"

if ! tmux has-session -t="$ts" 2> /dev/null; then
    tmux new-session -ds "$ts" "TERM=xterm-256color ssh $target"
fi

tmux switch-client -t "$ts"
tmux refresh-client -S
