#!/usr/bin/env bash


if tmux show -p @termpane &> /dev/null; then
    tmux last-pane
    exit 0
fi

existing=""
for t in $(tmux list-panes -F '#{pane_index}'); do
    if tmux show -p -t "$t" @termpane &> /dev/null; then
        existing=$t
    fi
done


if [[ -z "$existing" ]]; then
    tmux split-window -v -c "#{pane_current_path}" -l 50%
    tmux set -p @termpane yes
else
    tmux select-pane -t "$t"
    tmux resize-pane -y 50%
fi

