#!/bin/bash
set -e
if [ -z "$1" ]; then
    echo "usage: delmerged <branch>"
    exit 1
fi

git checkout "$1"
git pull --ff-only

# this will exit script if grep has no matches
purge=$(git branch --merged | grep -Ev "trunk|master|main|development|dev|\*|\+")

cat << "FOO"
___  _  _ ____ ____ ____    ____ ___ _  _ ____ ____
|__] |  | |__/ | __ |___    [__   |  |  | |___ |___
|    |__| |  \ |__] |___    ___]  |  |__| |    |

FOO

echo "$purge" | xargs -r -t -n1 git branch -d

