#!/usr/bin/env bash
set -e

printaction() {
    name=${FUNCNAME[1]}
    if command -v figlet &> /dev/null; then
        printf "\033[0;32m"
        echo "${name#install_} $1" | figlet
        printf "\033[0m\n"
    else
        echo "$name"
    fi
}

install_zsh() {
    printaction
    if ! command -v zsh; then
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    fi
    echo "zsh ok"
}

# ------------------------------------------------------------

install_nvim() {
    local version=v0.9.5
    printaction "$version"

    current=$(nvim -v | head -1 | cut -d ' ' -f2)
    if [ "$current" == "$version" ]; then
        echo up to date
        return
    fi

    wget https://github.com/neovim/neovim/releases/download/$version/nvim.appimage
    wget https://github.com/neovim/neovim/releases/download/$version/nvim.appimage.sha256sum

    sha256sum -c nvim.appimage.sha256sum
    rm nvim.appimage.sha256sum

    chmod u+x nvim.appimage
    mv nvim.appimage ~/.local/bin/nvim
    nvim --version
}

# ------------------------------------------------------------
install_formatters() {
    printaction
    npm i -g prettier
    npm i -g @fsouza/prettierd
}

# ------------------------------------------------------------
install_apt_packages() {
    printaction
    sudo apt update
    sudo apt install \
        zip \
        unzip \
        ripgrep \
        shellcheck \
        tmux \
        figlet
    sudo apt autoremove -y
}

install_nvm() {
    printaction
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
}

# ------------------------------------------------------------
install_fuck() {
    printaction
    sudo apt install python3-dev python3-pip python3-setuptools
    pip3 install --upgrade pip
    pip3 install thefuck --user
}

# ------------------------------------------------------------
install_python() {
    printaction
    sudo apt install software-properties-common 
    sudo add-apt-repository ppa:deadsnakes/ppa 
    sudo apt update
    sudo apt install python3.10 python3.10-venv python3-pip python3.10-dev
    sudo apt autoremove -y
}

# ------------------------------------------------------------
install_go() {
    local version=1.21.6
    local shasum=3f934f40ac360b9c01f616a9aa1796d227d8b0328bf64cb045c7b8c4ee9caea4

    printaction $version

    if [[ $(go version || true) == "go version go$version linux/amd64" ]]; then
        echo up to date
        return
    fi
    local pkg=go$version.linux-amd64.tar.gz
    wget https://go.dev/dl/$pkg
    sha256sum -c <<< "$shasum $pkg"
    sudo rm -rf /usr/local/go
    sudo tar -C /usr/local -xzf $pkg
    go version
}

# ------------------------------------------------------------

install_docker() {
    printaction
    sudo apt remove \
        docker \
        docker-engine \
        docker.io \
        containerd \
        runc
    
    sudo apt-get update
    sudo apt install ca-certificates curl gnupg

    sudo mkdir -m 0755 -p /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    echo \
        "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
        $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
        sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

    sudo apt update
    sudo apt install \
        docker-ce \
        docker-ce-cli \
        containerd.io \
        docker-buildx-plugin \
        docker-compose-plugin

    sudo apt autoremove -y
}
# ------------------------------------------------------------

install_fzf() {
    printaction
    ~/.fzf/install
    sudo apt install fd-find
    ln -s "$(command -v fdfind)" ~/.local/bin/fd
}

# ------------------------------------------------------------

install_bat() {
    printaction
    filename=bat-musl_0.23.0_amd64.deb
    wget "https://github.com/sharkdp/bat/releases/download/v0.23.0/$filename"
    sudo dpkg -i "$filename"
}

# ------------------------------------------------------------

if [[ $# -eq 0 ]]; then
    echo "zsh nvim python formatters apt_packages nvm fuck go docker fzf bat"
fi

while test $# -gt 0
do 
    case "$1" in 
        zsh)
            install_zsh
            ;;
        nvim)
            install_nvim
            ;;
        python)
            install_python
            ;;
        formatters)
            install_formatters
            ;;
        apt_packages)
            install_apt_packages
            ;;
        nvm)
            install_nvm
            ;;
        fuck)
            install_fuck
            ;;
        go)
            install_go
            ;;
        docker)
            install_docker
            ;;
        fzf)
            install_fzf
            ;;
        bat)
            install_bat
            ;;
        *)
            echo "invalid command: $1"
            ;;
    esac
    shift
done

