#!/usr/bin/env bash

fd --hidden --ignore-file "$XDG_CONFIG_HOME/git/ignore" --type directory . ~ \
    | fzf \
        --prompt ' ...' \
        --bind 'load:change-prompt:> ' \
        --query "$1" \
        --header='all folders' \
        --header-first \
        --tmux \
        --info=hidden
