#!/usr/bin/env bash

fd --hidden --no-ignore --type directory "\.git$" \
    "$HOME/.local/share" \
    "$HOME/git" \
    "$HOME/plugins" \
    | sed -e 's|/.git$||' \
    | fzf \
    --prompt ' ...' \
    --bind 'load:change-prompt:> ' \
    --query "$1" \
    --header='git projects' \
    --header-first \
    --tmux \
    --info=hidden
