#!/usr/bin/env bash

git remote update
local=$(git rev-parse HEAD)
remote=$(git rev-parse '@{upstream}')
base=$(git merge-base HEAD '@{upstream}')


if [ "$local" = "$remote" ]; then
    echo "Up to date" >&2
    exit 0
elif [ "$local" = "$base" ]; then
    echo "Need to pull" >&2
elif [ "$remote" = "$base" ]; then
    echo "Need to push" >&2
else
    echo "Diverged"
fi

git log 'HEAD^..@{upstream}' --oneline
exit 1
