#!/usr/bin/env bash

set -e

project=$(gitprojectfind "$1")

if [ -z "$project" ]; then
    exit 0
fi

sessari="$(basename "$project")"
sessari="${sessari//./-}"
if ! tmux has-session -t="$sessari" 2> /dev/null; then
    tmux new-session -ds "$sessari" -c "$project"
fi

if [ -z "$TMUX" ]; then
    tmux attach -t "$sessari"
else
    tmux switch-client -t "$sessari"
fi
tmux refresh-client -S
