#!/usr/bin/env bash


if [ -z "$TMUX" ]; then
    tmux new-session -s nvimconfig -c "$HOME" "GIT_DIR=$HOME/.dotfiles GIT_WORK_TREE=$HOME nvim"
else
    tmux new-window -n nvimconfig -c "$HOME" "GIT_DIR=$HOME/.dotfiles GIT_WORK_TREE=$HOME nvim"
fi

