#!/usr/bin/env python3


from pathlib import Path
from subprocess import run
import sys


def main():
    bgimage = Path("~/.bgimage").expanduser()
    current = None
    if bgimage.exists():
        current = Path(bgimage.read_text())

    images = sorted(list(Path("~/user/pictures/wallpapers/").expanduser().iterdir()))

    i = 0
    if current:
        i = images.index(current)

    image = images[(i + 1) % len(images)]
    bgimage.write_text(str(image))

    rc = run(
        f"feh --bg-fill {image}",
        shell=True,
    )
    if rc.returncode != 0:
        sys.exit(rc.returncode)


if __name__ == "__main__":
    main()
