#!/bin/bash

set -e

sshconfigs=$(rg 'host ([\w+\-_\.]+)$' -or "\$1" ~/.ssh/config)
etchosts=$(rg '^[\d\.]+\s+(\S+)' -or "\$1" /etc/hosts)

hosts=$(echo -e "$sshconfigs\n$etchosts" | sort -u)

target="$(echo "$hosts" | fzf --header "ssh" --header-first --info hidden --tmux)"
if [[ -z "$target" ]]; then
    exit 0
fi

ts="${target//_/-}"

if ! tmux has-session -t="$ts" 2> /dev/null; then
    tmux new-session -ds "$ts" "TERM=xterm-256color ssh $target"
fi

tmux switch-client -t "$ts"
tmux refresh-client -S
