#!/usr/bin/env bash

gray="\033[0;90m"
green="\033[0;32m"
yellow="\033[0;33m"
nocolor="\033[0;0m"

rt=$(pwd)
venvpath=""

printgray () {
    echo "${gray}$1${nocolor}"
}

while [[ -z $venvpath ]]
do
    if [[ "$(pwd)" == ~ ]]; then
            printgray "Hit home root, abort"
            break
    fi

    if [[ "$(pwd)" == / ]]; then
            printgray "Hit root, abort"
            break
    fi
    venvpath=$(fd -t f -I "activate$" | head -1)
    if [[ -z $venvpath ]];
    then
        printgray "fd -t f -I \"activate\$\" $(pwd) -> nah"
        cd ..
    else
        printgray "fd -t f -I \"activate\$\" $(pwd) -> oh"
        printgray "found $venvpath"
        . "$venvpath"
        echo "${green}OK: ${nocolor}VIRTUAL_ENV=$VIRTUAL_ENV"
        echo "${yellow}$(python -V)${nocolor}"
    fi
done

cd "$rt" || return
