#!/usr/bin/env python3


import sys
from datetime import datetime, timedelta

cycle_minutes = 30


def interval(ts: datetime) -> timedelta:
    return ts - datetime(
        ts.year, ts.month, ts.day, ts.hour, (ts.minute // cycle_minutes) * cycle_minutes
    )


until = timedelta(minutes=cycle_minutes) - interval(datetime.now())
print(f"{until.seconds//60}:{until.seconds%60:02}")

if until.seconds < 180:
    sys.exit(1)
